config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :trades
  resources :services
  resources :abouts
  resources :answers
  resources :authors
  resources :books
  resources :contacts

  resources :banners, only: [:new, :create, :index, :destroy]


  root :to => 'home#index',:as =>:root

  get 'home/index'

  get 'home/anwser_key'
  get 'home/trades'
  get    '/soba_admin_login',   to: 'sessions#new'
  post   '/soba_admin_login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '*path', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/answer.rb
class Answer < ApplicationRecord
  has_attached_file :pdf


  validates_attachment :pdf,
                        content_type: { content_type: ["application/pdf"] }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
has_and_belongs_to_many :books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
belongs_to :author
belongs_to :book
end

app/models/banner.rb
class Banner < ApplicationRecord

 has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
     convert_options: { thumb: "-quality 75 -strip",
                        original: "-quality 85 -strip" }


 validates_attachment :image,
                      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_attached_file :image,  styles: { thumb: ["400x300#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true
  validates :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX }
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  layout 'admin'
  before_action :logged_in_user
  # GET /services
  # GET /services.json
  def index
    @services = Service.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:title, :description, :status)

    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/answer_keys_helper.rb
module AnswerKeysHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session[:user_id] =nil
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?

      redirect_to root_path
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <%= render 'shared/errors', object: service %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field  :description, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label "Active" %>
    <%= form.check_box :status%>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>
<div class="link">
<%= link_to 'New Service', new_service_path %>
</div>
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      <% @services.each do |service| %>
        <div class="col-md-4 col-sm-6 portfolio-item">



          <div class="portfolio-caption">
            <h4><%= service.title %></h4>
            <p class="text-muted">Description:<%= service.description %></p>
            <p class="text-muted">Status:<%= service.status %></p>

            <p><%= link_to 'Show', service %></p>
            <p><%= link_to 'Edit', edit_service_path(service) %></p>
            <p><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></p>

          </div>

        </div>
      <% end %>

    </div>

  </div>
  </div>
  <%= will_paginate @services%>
</section>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">

        <div class="col-md-12 col-sm-12 portfolio-item">



          <div class="portfolio-caption">
            <h4><%= @service.title %></h4>
            <p class="text-muted">Description:<%= @service.description %></p>
            <p class="text-muted">Status:<%= @service.status %></p>

            <p><%= link_to 'Edit', edit_service_path(@service) %> | <%= link_to 'Back', services_path %></p>


          </div>

        </div>

    </div>
  </div>
  </div>
</section>