config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :trades
  resources :services
  resources :abouts
  resources :answers
  resources :authors
  resources :books
  resources :contacts

  resources :banners, only: [:new, :create, :index, :destroy]


  root :to => 'home#index',:as =>:root

  get 'home/index'

  get 'home/anwser_key'
  get 'home/trades'
  get    '/soba_admin_login',   to: 'sessions#new'
  post   '/soba_admin_login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '*path', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/answer.rb
class Answer < ApplicationRecord
  has_attached_file :pdf


  validates_attachment :pdf,
                        content_type: { content_type: ["application/pdf"] }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
has_and_belongs_to_many :books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
belongs_to :author
belongs_to :book
end

app/models/banner.rb
class Banner < ApplicationRecord

 has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
     convert_options: { thumb: "-quality 75 -strip",
                        original: "-quality 85 -strip" }


 validates_attachment :image,
                      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_attached_file :image,  styles: { thumb: ["400x300#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true
  validates :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX }
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  layout 'admin'
  before_action :logged_in_user

  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.order('created_at').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @author=Author.find(params[:id])

  end

  # GET /contacts/new
  def new
    @author = Author.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create


    @author = Author.new(author_params)
    respond_to do |format|
      if @author.save

        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author}
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update


    respond_to do |format|
      if @author.update(author_params)

        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:image, :name, :occupation, :qualification, :description,:twitter_url,:linked_in_url,:fb_url, :status)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/answer_keys_helper.rb
module AnswerKeysHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session[:user_id] =nil
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?

      redirect_to root_path
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_author.html.erb
<div class="col-md-4 col-sm-6 portfolio-item">

<p style="margin-top: 10px">
    <%=link_to image_tag(author.image.url, :alt => "", :class => "img-fluid") , author.image.url, target: '_blank' %>

</p>

  <div class="portfolio-caption">
    <h4><%=author.name%></h4>
    <p class="text-muted"><%=author.occupation%></p>
    <p class="text-muted"><%=author.qualification%></p>
    <p class="text-muted"><%=author.description%></p>
    <p><%= link_to 'Show',author %></p>
    <p><%= link_to 'Edit', edit_author_path(author) %></p>
    <p><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></p>

  </div>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: @author, local: true) do |f| %>
  <%= render 'shared/errors', object: @author %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= f.label :occupation %>
    <%= f.text_field  :occupation, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :qualification %>
    <%= f.text_field  :qualification, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field  :description, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :twitter_url %>
    <%= f.text_field  :twitter_url, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :linkedIn_url %>
    <%= f.text_field  :linked_in_url, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label :facebook_url %>
    <%= f.text_field  :fb_url, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label "Active" %>
    <%= f.check_box :status%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>
<div class="link">
<%= link_to 'Add New Author',  new_author_path %>
</div>
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
<%= render @authors %>
    </div>

  </div>
  </div>
  <%= will_paginate @authors%>
</section>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', contact: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">

      <div class="col-md-12 col-sm-12 portfolio-item">



        <div class="portfolio-caption">
          <h4><%= @author.name %></h4>
          <p class="text-muted">Occupation:<%= @author.occupation %></p>
          <p class="text-muted">Qualification:<%= @author.qualification %></p>
          <p class="text-muted">Description:<%= @author.description %></p>
          <p class="text-muted">Twitter URL:<%= @author.twitter_url %></p>
          <p class="text-muted">Facebook URL::<%= @author.fb_url %></p>
          <p class="text-muted">Linkedin URL:<%= @author.linked_in_url %></p>
          <p class="text-muted">Status:<%= @author.status %></p>
          <%=image_tag(@author.image.url, :alt => "", :class => "img-fluid") %>


          <p><%= link_to 'Edit', edit_author_path(@author) %> | <%= link_to 'Back', authors_path %></p>


        </div>

      </div>

    </div>
  </div>
  </div>
</section>