config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :trades
  resources :services
  resources :abouts
  resources :answers
  resources :authors
  resources :books
  resources :contacts

  resources :banners, only: [:new, :create, :index, :destroy]


  root :to => 'home#index',:as =>:root

  get 'home/index'

  get 'home/anwser_key'
  get 'home/trades'
  get    '/soba_admin_login',   to: 'sessions#new'
  post   '/soba_admin_login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '*path', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/answer.rb
class Answer < ApplicationRecord
  has_attached_file :pdf


  validates_attachment :pdf,
                        content_type: { content_type: ["application/pdf"] }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
has_and_belongs_to_many :books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
belongs_to :author
belongs_to :book
end

app/models/banner.rb
class Banner < ApplicationRecord

 has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
     convert_options: { thumb: "-quality 75 -strip",
                        original: "-quality 85 -strip" }


 validates_attachment :image,
                      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_attached_file :image,  styles: { thumb: ["400x300#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true
  validates :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX }
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :logged_in_user
  layout 'admin'
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:image, :title, :description, :time, :status)

    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/answer_keys_helper.rb
module AnswerKeysHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session[:user_id] =nil
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?

      redirect_to root_path
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, local: true) do |form| %>
  <%= render 'shared/errors', object: about %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field  :description, class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label "Active" %>
    <%= form.check_box :status%>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control'%>
  </div>
  <div class="form-group">
  <%= form.date_field :time, as: :date, value: form.object.try(:strftime,"%m/%d/%Y") %>
  </div>
  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abouts Data</h1>
<div class="link">
<%= link_to 'Add New Content',  new_about_path %>

</div>
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      <% @abouts.each do |about| %>
        <div class="col-md-4 col-sm-6 portfolio-item">



          <div class="portfolio-caption">
            <h4><%= about.title %></h4>
            <p class="text-muted">Description:<%= about.description %></p>
            <p class="text-muted">Status:<%= about.status %></p>

            <%=link_to image_tag(about.image.url, :alt => "", :class => "img-fluid") , about.image.url, target: '_blank' %>



            <p><%= link_to 'Show',about %></p>
            <p><%= link_to 'Edit', edit_about_path(about) %></p>
            <p><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></p>

          </div>

        </div>
      <% end %>

    </div>

  </div>
  </div>
  <%= will_paginate @abouts%>
</section>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">

      <div class="col-md-12 col-sm-12 portfolio-item">



        <div class="portfolio-caption">
          <h4><%= @about.title %></h4>
          <p class="text-muted">Description:<%= @about.description %></p>
          <p class="text-muted">Status:<%= @about.status %></p>
          <%=image_tag(@about.image.url, :alt => "", :class => "img-fluid") %>


          <p><%= link_to 'Edit', edit_about_path(@about) %> | <%= link_to 'Back', abouts_path %></p>


        </div>

      </div>

    </div>
  </div>
  </div>
</section>