config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :trades
  resources :services
  resources :abouts
  resources :answers
  resources :authors
  resources :books
  resources :contacts

  resources :banners, only: [:new, :create, :index, :destroy]


  root :to => 'home#index',:as =>:root

  get 'home/index'

  get 'home/anwser_key'
  get 'home/trades'
  get    '/soba_admin_login',   to: 'sessions#new'
  post   '/soba_admin_login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '*path', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/answer.rb
class Answer < ApplicationRecord
  has_attached_file :pdf


  validates_attachment :pdf,
                        content_type: { content_type: ["application/pdf"] }


end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
has_and_belongs_to_many :books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
belongs_to :author
belongs_to :book
end

app/models/banner.rb
class Banner < ApplicationRecord

 has_attached_file :image,  styles: { thumb: ["64x64#", :jpg],
                                       original: ['500x500>', :jpg] },
     convert_options: { thumb: "-quality 75 -strip",
                        original: "-quality 85 -strip" }


 validates_attachment :image,
                      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_attached_file :image,  styles: { thumb: ["400x300#", :jpg],
                                       original: ['500x500>', :jpg] },
                    convert_options: { thumb: "-quality 75 -strip",
                                       original: "-quality 85 -strip" }


  validates_attachment :image,
                       content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true
  validates :message, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX }
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/trade.rb
class Trade < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session[:user_id] =nil
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?

      redirect_to root_path
    end
  end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin_footer.html.erb
<div class="home">
<footer class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <ul class="nav pull-right">
        <li>
        <span class="copyright">Copyright &copy; Sobabooks 2018</span></li>
      </ul>



    </div>
  </div>
</footer>
</div>

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="header" style="color: black">
      <%= link_to "", contacts_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if logged_in? %>
            <li><%= link_to "Contact",   contacts_path %></li>
            <li><%= link_to "Services",   services_path %></li>
            <li><%= link_to "Answer Key", answers_path %></li>
            <li><%= link_to "About",   abouts_path %></li>
            <li><%= link_to "Books",   books_path %></li>
            <li><%= link_to "Authors",   authors_path %></li>
            <li><%= link_to "Traders",   trades_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account </b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Sobabooks 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-linkedin-in"></i>
            </a>
          </li>
        </ul>
      </div>

    </div>
  </div>
</footer>

<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl"></div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body" id="jibin">


            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<body id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <%= link_to(image_tag("main-logo.png", :alt => "logo", :class => "navbar-brand js-scroll-trigger"), root_path,{:style=>'width:0%', :method => :get})   %>

    <!--<a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>-->
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav text-uppercase ml-auto">
        <li class="nav-item">

          <a class="nav-link js-scroll-trigger" href="<%= current_page?(root_path) ? '#services' : '/#services' %>">What We Offer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="<%= current_page?(root_path) ? '#portfolio' : '/#portfolio' %>">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="<%= current_page?(root_path) ? '#about' : '/#about' %>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="<%= current_page?(root_path) ? '#team' : '/#team' %>">Authors</a>
        </li>
        <li  class="nav-item"><%= active_link_to 'Answer Key', home_anwser_key_path,:class => "nav-link js-scroll-trigger" %></li>
        <li  class="nav-item"><%= active_link_to 'Traders', home_trades_path,:class => "nav-link js-scroll-trigger" %></li>

        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="<%= current_page?(root_path) ? '#contact' : '/#contact' %>">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="apple-mobile-web-app-capable" content="yes">
      <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
      <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0">
      <meta name="keywords" content="MG University,Mcom,Bcom,GST Books">
      <meta name="description" content="Sobabooks.com">

      <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/admin_header' %>
  <div class="container">

    <%= yield %>

    <%= render 'layouts/admin_footer' %>

  </div>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sobabooks:Online GST book store</title>
    <meta charset="utf-8">
    <meta name="Title" content="Sobabooks: India's number one gst book store">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=2.0,minimum-scale=1.0">
    <meta name="keywords" content="Soba Books, anwser_key, answers, Book Store, Online Book Store, Online Book Store India, soba publications, MG University, M-com, B-com,GST book online, GST Books.">
    <meta name="description" content="Buy Online Income Tax books, GST books, Company Law, International Taxation, CA & CS books, B.Com Books from SOBABOOKS bookstore.">
    <%= favicon_link_tag asset_path('fav-icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper_header">
    <div class="row">
      <%= render "/layouts/header" %>
    </div>
  </div>
    <%= yield %>
  <%= render "/layouts/footer" %>
  </body>

</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>